#############################################################################
# Makefile for building: APP
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  APP.pro
# Template: subdirs
# Command: D:\Qt\Qt5.14.2\5.14.2\android\bin\qmake.exe -o Makefile APP.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\Qt5.14.2\5.14.2\android\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt5.14.2\5.14.2\android\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt5.14.2\5.14.2\android\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = cmd /c move
TAR           = 
COMPRESS      = 
DISTNAME      = APP1.0.0
DISTDIR = D:\projects\APP\.tmp\APP1.0.0
SUBTARGETS    =  \
		sub-DBManager \
		sub-Application


sub-DBManager-qmake_all:  FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a"
	cd DBManager\ && $(MAKE) -f Makefile qmake_all
sub-DBManager: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile
sub-DBManager-make_first-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile 
sub-DBManager-make_first: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile 
sub-DBManager-all-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile all
sub-DBManager-all: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile all
sub-DBManager-clean-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile clean
sub-DBManager-clean: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile clean
sub-DBManager-distclean-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile distclean
sub-DBManager-distclean: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile distclean
sub-DBManager-install_subtargets-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install
sub-DBManager-install_subtargets: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install
sub-DBManager-uninstall_subtargets-ordered: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile uninstall
sub-DBManager-uninstall_subtargets: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile uninstall
sub-Application-qmake_all: sub-DBManager-qmake_all FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a"
	cd Application\ && $(MAKE) -f Makefile qmake_all
sub-Application: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile
sub-Application-make_first-ordered: sub-DBManager-make_first-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile 
sub-Application-make_first: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile 
sub-Application-all-ordered: sub-DBManager-all-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile all
sub-Application-all: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile all
sub-Application-clean-ordered: sub-DBManager-clean-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile clean
sub-Application-clean: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile clean
sub-Application-distclean-ordered: sub-DBManager-distclean-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile distclean
sub-Application-distclean: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile distclean
sub-Application-install_subtargets-ordered: sub-DBManager-install_subtargets-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install
sub-Application-install_subtargets: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install
sub-Application-uninstall_subtargets-ordered: sub-DBManager-uninstall_subtargets-ordered  FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile uninstall
sub-Application-uninstall_subtargets: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile uninstall

sub-DBManager-sub-Application-install: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile install

Makefile: APP.pro ..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\android-clang\qmake.conf ..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\spec_pre.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\unix.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\linux.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\sanitize.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\gcc-base.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\gcc-base-unix.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\clang.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\qdevice.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\device_config.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\qconfig.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3drender.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_charts.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_repparser.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scxml.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webview.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qt_functions.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qt_config.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\android-clang\qmake.conf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\spec_post.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\spec_post.prf \
		.qmake.stash \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\toolchain.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\default_pre.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\default_pre.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\resolve_config.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\resolve_config.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exclusive_builds_post.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\default_post.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qml_debug.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\android.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\android_deployment_settings.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\warn_on.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qmake_use.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\file_copies.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\testcase_targets.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exceptions.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\yacc.prf \
		..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\lex.prf \
		APP.pro
	$(QMAKE) -o Makefile APP.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a"
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\spec_pre.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\unix.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\linux.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\sanitize.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\gcc-base.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\gcc-base-unix.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\common\clang.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\qdevice.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\device_config.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\qconfig.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3danimation.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dextras.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3drender.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_androidextras.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_charts.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_charts_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gamepad.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_location.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_networkauth.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_purchasing.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_repparser.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scxml.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qt_functions.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qt_config.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\android-clang\qmake.conf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\spec_post.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\spec_post.prf:
.qmake.stash:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exclusive_builds.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\toolchain.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\default_pre.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\default_pre.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\resolve_config.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\resolve_config.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\default_post.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qml_debug.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\android.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\android\android_deployment_settings.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\warn_on.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\qmake_use.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\file_copies.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\testcase_targets.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\exceptions.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\yacc.prf:
..\..\Qt\Qt5.14.2\5.14.2\android\mkspecs\features\lex.prf:
APP.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile APP.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a"

qmake_all: sub-DBManager-qmake_all sub-Application-qmake_all FORCE

make_first: sub-DBManager-make_first-ordered sub-Application-make_first-ordered  FORCE
all: sub-DBManager-all-ordered sub-Application-all-ordered  FORCE
clean: sub-DBManager-clean-ordered sub-Application-clean-ordered android-build-distclean FORCE
distclean: sub-DBManager-distclean-ordered sub-Application-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-DBManager-install_subtargets-ordered sub-Application-install_subtargets-ordered FORCE
uninstall_subtargets: sub-DBManager-uninstall_subtargets-ordered sub-Application-uninstall_subtargets-ordered FORCE

sub-DBManager-armeabi-v7a_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile armeabi-v7a
sub-Application-armeabi-v7a_ordered: sub-DBManager-armeabi-v7a_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile armeabi-v7a
armeabi-v7a: sub-DBManager-armeabi-v7a_ordered sub-Application-armeabi-v7a_ordered

android-build-distclean:
	rmdir /s /q D:\projects\APP\android-build

sub-DBManager-aab_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile aab
sub-Application-aab_ordered: sub-DBManager-aab_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile aab
aab: sub-DBManager-aab_ordered sub-Application-aab_ordered

sub-DBManager-apk_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile apk
sub-Application-apk_ordered: sub-DBManager-apk_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile apk
apk: sub-DBManager-apk_ordered sub-Application-apk_ordered

sub-DBManager-apk_install_target_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile apk_install_target
sub-Application-apk_install_target_ordered: sub-DBManager-apk_install_target_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile apk_install_target
apk_install_target: sub-DBManager-apk_install_target_ordered sub-Application-apk_install_target_ordered

sub-DBManager-check_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile check
sub-Application-check_ordered: sub-DBManager-check_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile check
check: sub-DBManager-check_ordered sub-Application-check_ordered

sub-DBManager-benchmark_ordered:
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile benchmark
sub-Application-benchmark_ordered: sub-DBManager-benchmark_ordered 
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-DBManager-benchmark_ordered sub-Application-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-DBManager-distdir sub-Application-distdir FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents  $(DISTDIR)\

sub-DBManager-distdir: FORCE
	@if not exist DBManager\ mkdir DBManager\ & if not exist DBManager\ exit 1
	cd DBManager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\DBManager\DBManager.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\DBManager

sub-Application-distdir: FORCE
	@if not exist Application\ mkdir Application\ & if not exist Application\ exit 1
	cd Application\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\projects\APP\Application\Application.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a" ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\Application

